a = int(input('b:'))
b = int(input('a:'))
print('a)', 1/7 * a**3 * b - 2 * a * b**2 * (a + b))
print('б)', 2 * a + (3 * a - b)**2)
print('в)', 3 * a**2 * b + 2 * a / (a - 4 * b))
print('г)', (2 * a - 3 * b)**2 / (3 * a - 4 * b**2))
print('д)', (3 * a**3 - 2 * a * b + b**2) / 2 * a * (3 * a - b))
print('е)', (2 * a**2 - 3 * a * b) / ((a - 3*b)**2 - (7 * a - 4 * b)**2))
